-- ENUM TYPES
CREATE TYPE restaurant_status_enum AS ENUM ('active', 'inactive', 'closed');
CREATE TYPE order_status_enum AS ENUM ('pending', 'preparing', 'delivered', 'cancelled');
CREATE TYPE discount_type_enum AS ENUM ('percent', 'fixed');

-- USERS
CREATE TABLE users (
  user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL,
  email varchar(100) UNIQUE NOT NULL,
  password varchar(255) NOT NULL,
  phone_number varchar(15),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by int,
  updated_by int,
  is_deleted boolean DEFAULT false
);

-- USER ADDRESSES
CREATE TABLE user_addresses (
  address_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id int NOT NULL,
  address_line text NOT NULL,
  city varchar(50),
  state varchar(50),
  pincode varchar(10),
  is_default boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by int,
  updated_by int,
  is_deleted boolean DEFAULT false,
  CONSTRAINT unique_default_address_per_user UNIQUE(user_id, is_default)
);

-- RESTAURANTS
CREATE TABLE restaurants (
  restaurant_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(150) NOT NULL,
  address text,
  phone_number varchar(15),
  status restaurant_status_enum DEFAULT 'active',
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by int,
  updated_by int,
  is_deleted boolean DEFAULT false
);

-- MENU ITEMS
CREATE TABLE menu_items (
  item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id int NOT NULL,
  name varchar(150) NOT NULL,
  description text,
  price decimal(8,2) NOT NULL,
  is_veg boolean,
  is_available boolean,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by int,
  updated_by int,
  is_deleted boolean DEFAULT false
);

-- OFFERS
CREATE TABLE offers (
  offer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(50) UNIQUE NOT NULL,
  description text,
  discount_type discount_type_enum,
  discount_value decimal(8,2),
  min_order_amount decimal(10,2),
  max_discount_amount decimal(10,2),
  valid_from date,
  valid_to date,
  is_active boolean,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by int,
  updated_by int,
  is_deleted boolean DEFAULT false
);

-- CART
CREATE TABLE cart (
  cart_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id int UNIQUE NOT NULL,
  restaurant_id int NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by int,
  updated_by int,
  is_deleted boolean DEFAULT false
);

-- CART ITEMS
CREATE TABLE cart_items (
  cart_item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cart_id int NOT NULL,
  item_id int NOT NULL,
  quantity int NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by int,
  updated_by int,
  is_deleted boolean DEFAULT false
);

-- ORDERS
CREATE TABLE orders (
  order_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id int NOT NULL,
  restaurant_id int NOT NULL,
  offer_id int,
  total_amount decimal(10,2) NOT NULL,
  discount_amount decimal(10,2),
  final_amount decimal(10,2) NOT NULL,
  order_status order_status_enum DEFAULT 'pending',
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by int,
  updated_by int,
  is_deleted boolean DEFAULT false
);

-- ORDER ITEMS
CREATE TABLE order_items (
  order_item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id int NOT NULL,
  item_id int NOT NULL,
  quantity int NOT NULL,
  price decimal(8,2) NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by int,
  updated_by int,
  is_deleted boolean DEFAULT false
);

-- ORDER RATINGS
CREATE TABLE order_ratings (
  rating_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id int UNIQUE NOT NULL,
  user_id int NOT NULL,
  restaurant_id int NOT NULL,
  rating int CHECK (rating >= 1 AND rating <= 5),
  review text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by int,
  updated_by int,
  is_deleted boolean DEFAULT false
);

-- FOREIGN KEYS
ALTER TABLE user_addresses ADD FOREIGN KEY (user_id) REFERENCES users(user_id) DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE menu_items ADD FOREIGN KEY (restaurant_id) REFERENCES restaurants(restaurant_id) DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE cart ADD FOREIGN KEY (user_id) REFERENCES users(user_id) DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE cart ADD FOREIGN KEY (restaurant_id) REFERENCES restaurants(restaurant_id) DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE cart_items ADD FOREIGN KEY (cart_id) REFERENCES cart(cart_id) DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE cart_items ADD FOREIGN KEY (item_id) REFERENCES menu_items(item_id) DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE orders ADD FOREIGN KEY (user_id) REFERENCES users(user_id) DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE orders ADD FOREIGN KEY (restaurant_id) REFERENCES restaurants(restaurant_id) DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE orders ADD FOREIGN KEY (offer_id) REFERENCES offers(offer_id) DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE order_items ADD FOREIGN KEY (order_id) REFERENCES orders(order_id) DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE order_items ADD FOREIGN KEY (item_id) REFERENCES menu_items(item_id) DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE order_ratings ADD FOREIGN KEY (order_id) REFERENCES orders(order_id) DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE order_ratings ADD FOREIGN KEY (user_id) REFERENCES users(user_id) DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE order_ratings ADD FOREIGN KEY (restaurant_id) REFERENCES restaurants(restaurant_id) DEFERRABLE INITIALLY IMMEDIATE;

-- PARTIAL INDEXES FOR SOFT DELETE
CREATE INDEX idx_active_users ON users(user_id) WHERE is_deleted = false;
CREATE INDEX idx_active_addresses ON user_addresses(address_id) WHERE is_deleted = false;
CREATE INDEX idx_active_restaurants ON restaurants(restaurant_id) WHERE is_deleted = false;
CREATE INDEX idx_active_menu_items ON menu_items(item_id) WHERE is_deleted = false;
CREATE INDEX idx_active_offers ON offers(offer_id) WHERE is_deleted = false;
CREATE INDEX idx_active_cart ON cart(cart_id) WHERE is_deleted = false;
CREATE INDEX idx_active_cart_items ON cart_items(cart_item_id) WHERE is_deleted = false;
CREATE INDEX idx_active_orders ON orders(order_id) WHERE is_deleted = false;
CREATE INDEX idx_active_order_items ON order_items(order_item_id) WHERE is_deleted = false;
CREATE INDEX idx_active_order_ratings ON order_ratings(rating_id) WHERE is_deleted = false;

-- TRIGGER FOR UPDATED_AT
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply trigger on tables
DO $$
DECLARE
    tbl text;
BEGIN
    FOR tbl IN
        SELECT table_name
        FROM information_schema.tables
        WHERE table_schema='public' AND table_name IN (
            'users','user_addresses','restaurants','menu_items','offers',
            'cart','cart_items','orders','order_items','order_ratings'
        )
    LOOP
        EXECUTE format('CREATE TRIGGER trg_%I_updated_at BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION update_updated_at();', tbl, tbl);
    END LOOP;
END$$;