"""Add is_active column to User

Revision ID: ebb6a69569a5
Revises: 4b63af5d39dc
Create Date: 2026-04-17 09:35:28.627616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ebb6a69569a5'
down_revision: Union[str, Sequence[str], None] = '4b63af5d39dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cart', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cart', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_active_cart'), table_name='cart', postgresql_where='(is_deleted = false)')
    op.drop_constraint(op.f('cart_user_id_fkey'), 'cart', type_='foreignkey')
    op.drop_constraint(op.f('cart_restaurant_id_fkey'), 'cart', type_='foreignkey')
    op.create_foreign_key(None, 'cart', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'cart', 'restaurants', ['restaurant_id'], ['restaurant_id'])
    op.alter_column('cart_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cart_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cart_items', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_active_cart_items'), table_name='cart_items', postgresql_where='(is_deleted = false)')
    op.drop_constraint(op.f('cart_items_item_id_fkey'), 'cart_items', type_='foreignkey')
    op.drop_constraint(op.f('cart_items_cart_id_fkey'), 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'menu_items', ['item_id'], ['item_id'])
    op.create_foreign_key(None, 'cart_items', 'cart', ['cart_id'], ['cart_id'])
    op.alter_column('menu_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('menu_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('menu_items', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_active_menu_items'), table_name='menu_items', postgresql_where='(is_deleted = false)')
    op.drop_constraint(op.f('menu_items_restaurant_id_fkey'), 'menu_items', type_='foreignkey')
    op.create_foreign_key(None, 'menu_items', 'restaurants', ['restaurant_id'], ['restaurant_id'])
    op.alter_column('offers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('offers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('offers', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_active_offers'), table_name='offers', postgresql_where='(is_deleted = false)')
    op.alter_column('order_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('order_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('order_items', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_active_order_items'), table_name='order_items', postgresql_where='(is_deleted = false)')
    op.drop_constraint(op.f('order_items_item_id_fkey'), 'order_items', type_='foreignkey')
    op.drop_constraint(op.f('order_items_order_id_fkey'), 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['order_id'])
    op.create_foreign_key(None, 'order_items', 'menu_items', ['item_id'], ['item_id'])
    op.alter_column('order_ratings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('order_ratings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('order_ratings', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_active_order_ratings'), table_name='order_ratings', postgresql_where='(is_deleted = false)')
    op.drop_constraint(op.f('order_ratings_restaurant_id_fkey'), 'order_ratings', type_='foreignkey')
    op.drop_constraint(op.f('order_ratings_user_id_fkey'), 'order_ratings', type_='foreignkey')
    op.drop_constraint(op.f('order_ratings_order_id_fkey'), 'order_ratings', type_='foreignkey')
    op.create_foreign_key(None, 'order_ratings', 'orders', ['order_id'], ['order_id'])
    op.create_foreign_key(None, 'order_ratings', 'restaurants', ['restaurant_id'], ['restaurant_id'])
    op.create_foreign_key(None, 'order_ratings', 'users', ['user_id'], ['user_id'])
    op.alter_column('orders', 'order_status',
               existing_type=postgresql.ENUM('pending', 'preparing', 'delivered', 'cancelled', name='order_status_enum'),
               nullable=False,
               existing_server_default=sa.text("'pending'::order_status_enum"))
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_active_orders'), table_name='orders', postgresql_where='(is_deleted = false)')
    op.drop_constraint(op.f('orders_user_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_offer_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_restaurant_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'restaurants', ['restaurant_id'], ['restaurant_id'])
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'orders', 'offers', ['offer_id'], ['offer_id'])
    op.alter_column('restaurants', 'status',
               existing_type=postgresql.ENUM('active', 'inactive', 'closed', name='restaurant_status_enum'),
               nullable=False,
               existing_server_default=sa.text("'active'::restaurant_status_enum"))
    op.alter_column('restaurants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('restaurants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('restaurants', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_active_restaurants'), table_name='restaurants', postgresql_where='(is_deleted = false)')
    op.alter_column('user_addresses', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('user_addresses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_addresses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_addresses', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_active_addresses'), table_name='user_addresses', postgresql_where='(is_deleted = false)')
    op.drop_constraint(op.f('user_addresses_user_id_fkey'), 'user_addresses', type_='foreignkey')
    op.create_foreign_key(None, 'user_addresses', 'users', ['user_id'], ['user_id'])
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_active_users'), table_name='users', postgresql_where='(is_deleted = false)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_active_users'), 'users', ['user_id'], unique=False, postgresql_where='(is_deleted = false)')
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'is_active')
    op.drop_constraint(None, 'user_addresses', type_='foreignkey')
    op.create_foreign_key(op.f('user_addresses_user_id_fkey'), 'user_addresses', 'users', ['user_id'], ['user_id'], deferrable=True)
    op.create_index(op.f('idx_active_addresses'), 'user_addresses', ['address_id'], unique=False, postgresql_where='(is_deleted = false)')
    op.alter_column('user_addresses', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('user_addresses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_addresses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_addresses', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('idx_active_restaurants'), 'restaurants', ['restaurant_id'], unique=False, postgresql_where='(is_deleted = false)')
    op.alter_column('restaurants', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('restaurants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('restaurants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('restaurants', 'status',
               existing_type=postgresql.ENUM('active', 'inactive', 'closed', name='restaurant_status_enum'),
               nullable=True,
               existing_server_default=sa.text("'active'::restaurant_status_enum"))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_restaurant_id_fkey'), 'orders', 'restaurants', ['restaurant_id'], ['restaurant_id'], deferrable=True)
    op.create_foreign_key(op.f('orders_offer_id_fkey'), 'orders', 'offers', ['offer_id'], ['offer_id'], deferrable=True)
    op.create_foreign_key(op.f('orders_user_id_fkey'), 'orders', 'users', ['user_id'], ['user_id'], deferrable=True)
    op.create_index(op.f('idx_active_orders'), 'orders', ['order_id'], unique=False, postgresql_where='(is_deleted = false)')
    op.alter_column('orders', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'order_status',
               existing_type=postgresql.ENUM('pending', 'preparing', 'delivered', 'cancelled', name='order_status_enum'),
               nullable=True,
               existing_server_default=sa.text("'pending'::order_status_enum"))
    op.drop_constraint(None, 'order_ratings', type_='foreignkey')
    op.drop_constraint(None, 'order_ratings', type_='foreignkey')
    op.drop_constraint(None, 'order_ratings', type_='foreignkey')
    op.create_foreign_key(op.f('order_ratings_order_id_fkey'), 'order_ratings', 'orders', ['order_id'], ['order_id'], deferrable=True)
    op.create_foreign_key(op.f('order_ratings_user_id_fkey'), 'order_ratings', 'users', ['user_id'], ['user_id'], deferrable=True)
    op.create_foreign_key(op.f('order_ratings_restaurant_id_fkey'), 'order_ratings', 'restaurants', ['restaurant_id'], ['restaurant_id'], deferrable=True)
    op.create_index(op.f('idx_active_order_ratings'), 'order_ratings', ['rating_id'], unique=False, postgresql_where='(is_deleted = false)')
    op.alter_column('order_ratings', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('order_ratings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('order_ratings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key(op.f('order_items_order_id_fkey'), 'order_items', 'orders', ['order_id'], ['order_id'], deferrable=True)
    op.create_foreign_key(op.f('order_items_item_id_fkey'), 'order_items', 'menu_items', ['item_id'], ['item_id'], deferrable=True)
    op.create_index(op.f('idx_active_order_items'), 'order_items', ['order_item_id'], unique=False, postgresql_where='(is_deleted = false)')
    op.alter_column('order_items', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('order_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('order_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_active_offers'), 'offers', ['offer_id'], unique=False, postgresql_where='(is_deleted = false)')
    op.alter_column('offers', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('offers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('offers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'menu_items', type_='foreignkey')
    op.create_foreign_key(op.f('menu_items_restaurant_id_fkey'), 'menu_items', 'restaurants', ['restaurant_id'], ['restaurant_id'], deferrable=True)
    op.create_index(op.f('idx_active_menu_items'), 'menu_items', ['item_id'], unique=False, postgresql_where='(is_deleted = false)')
    op.alter_column('menu_items', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('menu_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('menu_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key(op.f('cart_items_cart_id_fkey'), 'cart_items', 'cart', ['cart_id'], ['cart_id'], deferrable=True)
    op.create_foreign_key(op.f('cart_items_item_id_fkey'), 'cart_items', 'menu_items', ['item_id'], ['item_id'], deferrable=True)
    op.create_index(op.f('idx_active_cart_items'), 'cart_items', ['cart_item_id'], unique=False, postgresql_where='(is_deleted = false)')
    op.alter_column('cart_items', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('cart_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cart_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_foreign_key(op.f('cart_restaurant_id_fkey'), 'cart', 'restaurants', ['restaurant_id'], ['restaurant_id'], deferrable=True)
    op.create_foreign_key(op.f('cart_user_id_fkey'), 'cart', 'users', ['user_id'], ['user_id'], deferrable=True)
    op.create_index(op.f('idx_active_cart'), 'cart', ['cart_id'], unique=False, postgresql_where='(is_deleted = false)')
    op.alter_column('cart', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('cart', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cart', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
